[ENG-1159] Add setting and tests to file uploads for IA
CenterForOpenScience/osf-pigeon pull request #1
Opened 2019-11-12 18:02 UTC by Johnetordoff

## Purpose

Upload a series of nested directories to to Internet Archive

## Changes

- add script with tests for IA upload

## QA Notes

- not user facing, no migrations 

## Documentation

Not user facing.

## Side Effects

None that I know of.

## Ticket

https://openscience.atlassian.net/browse/ENG-1159

2019-11-13 22:00 UTC, corbinSanders requested changes

2019-11-13 22:00 UTC, corbinSanders commented on IA/IA_upload.py
> +async def upload(bucket_name: str, filename: str, file_content: bytes):
As we discussed in flowdock, not sure if a regular upload will be necessary. It depends on the max size of a non-chunk upload.

2019-11-13 22:00 UTC, corbinSanders commented on IA/tests/test_upload.py
> +        asyncio.run(upload('bucketname', 'file_name', b'content'))
You probably have already looked into this, but would there be a better way to mock these? It looks like the only assertions these do is making sure it doesn't error out.

2019-11-13 22:00 UTC, corbinSanders commented on IA/IA_upload.py
> +async def gather_and_upload(bucket_name: str, parent: str):
More Py3 💪

2019-11-15 15:21 UTC, Johnetordoff commented on IA/tests/test_upload.py
> +        asyncio.run(upload('bucketname', 'file_name', b'content'))
Yeah it's pretty difficult to mock.

2019-11-18 16:11 UTC, brianjgeiger requested changes
Only one small gitignore problem, otherwise looks good.

2019-11-18 16:11 UTC, brianjgeiger commented on settings/locals.py
> +OSF_API_URL = 'https://localhost:8000/'
Should this file be ignored? It looks like it's meant to be.

2019-11-18 16:25 UTC, brianjgeiger approved these changes

2019-11-18 16:31 UTC, merged