[ENG-1999][WIP] change pigeon
CenterForOpenScience/osf-pigeon pull request #18
Opened 2020-07-16 14:34 UTC by Johnetordoff

## Purpose

## Changes

## QA Notes

  - Does this change require a data migration? If so, what data will we migrate?
  - What is the level of risk?
    - Any permissions code touched?
    - Is this an additive or subtractive change, other?
  - How can QA verify? (Through UI, API, AdminApp or AdminAdminApp?)
    - If verifying through API, what's the new version? Please include the endpoints in PR notes or Dev docs.
  - What features or workflows might this change impact?
  - How will this impact performance?
-->

## Documentation

## Side Effects

## Ticket

https://openscience.atlassian.net/browse/ENG-1999

2020-07-17 19:35 UTC, corbinSanders requested changes
Looks good! Thank you for all the refactoring, John! I just have a few questions.

2020-07-17 19:35 UTC, corbinSanders commented on osf_pigeon/pigeon.py
> +            metadata=metadata,
I appreciate the desire to consolidate the metadata upload into one function. However I am unsure if the IA library will update the metadata if the item already exists.

2020-07-17 19:35 UTC, corbinSanders commented on osf_pigeon/pigeon.py
> +def put_with_retry(
I don't see anywhere we need to do a put.

2020-07-17 20:28 UTC, corbinSanders approved these changes
LGTM! Thanks again!

2020-07-20 18:22 UTC, brianjgeiger requested changes
A few tiny things, and a couple of comments. Otherwise looks great.

2020-07-20 18:22 UTC, brianjgeiger commented on osf_pigeon/__main__.py
> +        '-dp',
This should be either a single letter or should have a double-dash. `-p` should be fine.

2020-07-20 18:22 UTC, brianjgeiger commented on osf_pigeon/__main__.py
> +        '-du',
This should be either a single letter or should have a double-dash. `-u` should be fine

2020-07-20 18:22 UTC, brianjgeiger commented on osf_pigeon/__main__.py
> +        '-iaak',
This should be either a single letter or should have a double-dash. `-a` should be fine.

2020-07-20 18:22 UTC, brianjgeiger commented on osf_pigeon/__main__.py
> +        '-iask',
This should be either a single letter or should have a double-dash. `-s` should be fine.

2020-07-20 18:22 UTC, brianjgeiger commented on osf_pigeon/pigeon.py
> +        assert isinstance(ia_access_key, str),\
Could these assertions come before we grab all of the data from OSF?

2020-07-20 18:22 UTC, brianjgeiger commented on osf_pigeon/pigeon.py
> +        assert settings.OSF_BEARER_TOKEN, 'must have OSF_BEARER_TOKEN set to disable throttle'
Technically this will just make the throttling less likely. You could still be throttled if you're using a token.

2020-07-20 19:51 UTC, brianjgeiger approved these changes

2020-07-21 17:55 UTC, merged