Pigeon 2 server
CenterForOpenScience/osf-pigeon pull request #25
Opened 2021-02-18 19:41 UTC by Johnetordoff

## Purpose

## Changes

## QA Notes

  - Does this change require a data migration? If so, what data will we migrate?
  - What is the level of risk?
    - Any permissions code touched?
    - Is this an additive or subtractive change, other?
  - How can QA verify? (Through UI, API, AdminApp or AdminAdminApp?)
    - If verifying through API, what's the new version? Please include the endpoints in PR notes or Dev docs.
  - What features or workflows might this change impact?
  - How will this impact performance?
-->

## Documentation

## Side Effects

## Ticket

2021-02-23 14:42 UTC, corbinSanders commented on setup.py
> +    version="0.0.9",
I say we go ahead and bump to 0.1.0 or 0.0.10. The changes here are too big to keep the version the same.

2021-02-24 18:32 UTC, corbinSanders commented on osf_pigeon/pigeon.py
>  def modify_metadata_with_retry(ia_item, metadata, retries=2, sleep_time=60):
60 seconds is a long time to sleep. Would 10 seconds be sufficient?

2021-03-12 18:21 UTC, corbinSanders approved these changes
Looks good!

2021-03-15 18:59 UTC, jwalz reviewed
A couple things from group review:
use `?related_counts=true` to get the file counts and avoid fetching the empty zip
Add bibliographic contributors when formatting metadata (confirm full list with product)

2021-03-18 12:51 UTC, Johnetordoff commented
@jwalz I've done the disscussed things, is this good to be merged?

2021-03-29 14:02 UTC, jwalz requested changes
Forgot I had some nits hanging around. If you want to handle those as part of a broader cleanup PR, let me know.

2021-03-29 14:02 UTC, jwalz commented on osf_pigeon/__main__.py
> +    if future._exception:
why `future._exception` instead of `future.exception()`? same with `_result` vs `result()`? Yes, this is a callback, so we know that we don't need the blocking aspects of the function call, but we should respect the implicit protections in the interface.

2021-03-29 14:02 UTC, jwalz commented on osf_pigeon/pigeon.py
> +def get_id(guid):
This could be replaced by a format-able string constant:
```
ID_TEMPLATE = f'osf-registrations-{{guid}}-{settings.ID_VERSION}'

id = ID_TEMPLATE.format(guid=guid)
```
Same with get_provider_id below.

If you want to keep these as functions, I would at least make the signatures consistent (why does one take the guid pre-extracted while the other takes the full metadata blob?) as well as the names (this would be something like `get_document_id` or `get_resource_id`).

2021-03-29 14:02 UTC, jwalz commented on osf_pigeon/pigeon.py
>              retries -= 1
nit: prefer looping to recursing when the logic is this simple. Also, I endorse Corbin's suggestion that 60 seconds is a looong sleep. Please reduce or provide some documentation if this has been confirmed as necessary experimentally.

2021-03-29 14:02 UTC, jwalz commented on osf_pigeon/pigeon.py
> +    else:
nit: no need for `else` since the conditional raises an exception. This is the "standard" flow of the function, not a true condition.

2021-03-29 14:02 UTC, jwalz commented on osf_pigeon/pigeon.py
> +def run(main):
not: calling the arg `main` is very counterintuitive, since we also have a function called `main`. Make this something like `run(async_fn)` or `run(coroutine)`?

2021-03-29 14:02 UTC, jwalz commented on osf_pigeon/__main__.py
> +async def metadata(request, guid):
nit: function names generally make more sense as verbs. Pretty sure you can call this `set_metadata` or `sync_metadata` and keep the API path as-is.

2021-03-29 14:02 UTC, jwalz commented on osf_pigeon/__main__.py
> +from osf_pigeon.pigeon import main, sync_metadata, get_id
nit: please just import the module to provide visible namespacing and context on these function calls.

2021-03-29 14:02 UTC, jwalz commented on osf_pigeon/pigeon.py
> +    :return:
nit: incomplete docstring

2021-03-29 14:02 UTC, jwalz commented on osf_pigeon/pigeon.py
> +    :return:
nit: incomplete/incorrect docstring

2021-03-29 14:02 UTC, jwalz commented on osf_pigeon/pigeon.py
> +async def main(guid):
This isn't a script (anymore?), so calling this `main` is a little weird.

2021-03-29 14:02 UTC, jwalz commented on osf_pigeon/pigeon.py
> +        f"{settings.OSF_API_URL}v2/guids/{guid}/?embed=parent&embed=children&version=2.20"
For my own curiosity, why `/guids/` and not `/registrations/`?

2021-03-29 14:02 UTC, jwalz commented on osf_pigeon/pigeon.py
> +                task.result()
This whole mess mixing ThreadPoolExecutor with coroutines and the custom run function feels way overly complicated.

In an ideal, purely async world, we could just call `await asyncio.wait(tasks)`, but it looks like that gets messed up by our retry library, which calls `time.sleep` (instead of being smart enough to conditionally call `asyncio.sleep`) and pauses all of the coroutines on the event loop.

As such, I think that we should just purely do this block with the ThreadPoolExecutors and leave `get_pages` and `get_paginated_data` as the only async functions. From my testing, callers of `get_paginated_data` should be able to call it with `asyncio.run()` just fine.

That lets us get rid of the extra run function and keeps us from the overhead of needing to manage event loops *and* threads in ways that seem unnecessary.

2021-03-29 14:02 UTC, jwalz commented on osf_pigeon/pigeon.py
> +    :return:
nit: incomplete docstring

2021-03-29 14:02 UTC, jwalz commented on osf_pigeon/pigeon.py
> +    :return:
nit: incomplete docstring

2021-03-29 17:29 UTC, Johnetordoff commented on osf_pigeon/pigeon.py
>              retries -= 1
With the subcollection code gone, this doesn't really need a retry any more, so I just removed it.

2021-03-29 19:42 UTC, Johnetordoff commented on osf_pigeon/__main__.py
> +    if future._exception:
When they are called with the underscore they are called without printing a traceback or sysout. This made it easier to test several hundred registrations, but it's probably good to change it back now.

2021-03-30 12:22 UTC, Johnetordoff commented on osf_pigeon/pigeon.py
> +def get_id(guid):
Agreed the `get_id`'s were initially more complicated to deal with sub-collection issues, but are vestigial.

2021-03-30 12:25 UTC, Johnetordoff commented on osf_pigeon/pigeon.py
> +        f"{settings.OSF_API_URL}v2/guids/{guid}/?embed=parent&embed=children&version=2.20"
This was actually from something Corbin wrote, but appears to be the same as `/registrations/` so I changed it.

2021-03-30 14:48 UTC, jwalz approved these changes

2021-03-30 14:49 UTC, merged